#!/usr/bin/env node
// Mirrors runtime-independent modules from lib/mcp/ into the browser extension.
// The extension is loaded with `extension/` as its package root, so it cannot
// import across that boundary at runtime — the files must physically exist there.
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const MIRRORS = [
  { from: 'lib/mcp/icon-validation.mjs', to: 'extension/shared/icon-validation.js' },
];

const HEADER = [
  '// @generated by scripts/sync-shared.mjs — do not edit by hand.',
  '// Source of truth: lib/mcp/icon-validation.mjs',
  '// Regenerate with: npm run sync:shared',
  '',
].join('\n');

function render(from) {
  return HEADER + readFileSync(join(root, from), 'utf8');
}

const check = process.argv.includes('--check');
let drifted = 0;

for (const { from, to } of MIRRORS) {
  const expected = render(from);
  const target = join(root, to);

  if (check) {
    let actual = null;
    try {
      actual = readFileSync(target, 'utf8');
    } catch {}
    if (actual !== expected) {
      console.error(`out of sync: ${to} — run \`npm run sync:shared\``);
      drifted += 1;
    }
    continue;
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, expected);
  console.log(`synced ${from} -> ${to}`);
}

if (check) {
  if (drifted) process.exit(1);
  console.log('shared modules are in sync');
}
